# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keti', '0004_auto_20170829_1500'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertable',
            table='User_table',
        ),
    ]
